# Build Executable

  all: 
	mpicc -g -Wall -o ./build/ejercicio1A ejercicio1A.c

	mpicc -g -Wall -o ./build/ejercicio1B ejercicio1B.c

	mpicc -g -Wall -o ./build/ejercicio1C ejercicio1C.c

	mpicc -g -Wall -o ./build/ejercicio1D ejercicio1D.c

  clean: 
	$(RM) ./build/ejercicio*
